/* assets.h - OPEN WORLD art: AUTO-GENERATED by tools/gen_assets.py from the assets/ directory.
 * DO NOT EDIT: edit the ASCII sources and run `make assets` (python3 tools/gen_assets.py).
 * Contract: docs/CONTRACTS.md ("Assets").
 *
 * ART RULE: BG colour index 0 is LIGHT (fire, beacon light, stars, glints, glow). Ground is
 * colour 1, detail 2, deep shadow 3. The night palette crushes 1-3 and keeps 0 bright.
 * Sprite colours: 0 transparent, 1 light, 2 mid, 3 dark (for every sprite).
 */
#ifndef OPEN_WORLD_ASSETS_H
#define OPEN_WORLD_ASSETS_H

#include <stdint.h>
#include "world.h"            /* MT_COUNT */

/* BANKED: every array in this file lives in the switchable ROM bank BANK(assets)
   (autobanked). The engine must SWITCH_ROM(BANK(assets)) (and restore its own bank)
   before reading any of them, or copy what it needs to WRAM first. The #defines are
   plain constants and need no banking. */
#ifdef __SDCC
#include <gb/gb.h>
BANKREF_EXTERN(assets)
#endif
#define ASSETS_BANKED 1

/* ---- world BG tileset (load with set_bkg_data(0, BG_TILE_COUNT, bg_tiles)) ---- */
#define BG_TILE_COUNT  166    /* <= 224 */
extern const uint8_t bg_tiles[];              /* BG_TILE_COUNT * 16 bytes, 2bpp */
extern const uint8_t mt_tiles[MT_COUNT][4];   /* bg tile index TL, TR, BL, BR */
extern const uint8_t mt_attr[MT_COUNT][4];    /* CGB attribute: palette class (PAL_*), no flips */

/* Animated BG tiles: every ANIM_PERIOD frames copy anim_frames[i][f] into bg tile
   anim_tile[i], f = 0..ANIM_FRAMES-1 cycling. Entries: 0=SEA, 1=GLINT, 2=FIRE_L, 3=FIRE_R, 4=BEACON_L, 5=BEACON_R, 6=HEART_L, 7=HEART_R. */
#define ANIM_COUNT   8
#define ANIM_FRAMES  4
#define ANIM_PERIOD  16
#define ANIM_SEA      0   /* bg tile 1 */
#define ANIM_GLINT    1   /* bg tile 2 */
#define ANIM_FIRE_L   2   /* bg tile 3 */
#define ANIM_FIRE_R   3   /* bg tile 4 */
#define ANIM_BEACON_L 4   /* bg tile 5 */
#define ANIM_BEACON_R 5   /* bg tile 6 */
#define ANIM_HEART_L  6   /* bg tile 7 */
#define ANIM_HEART_R  7   /* bg tile 8 */
extern const uint8_t anim_tile[ANIM_COUNT];
extern const uint8_t anim_frames[ANIM_COUNT][ANIM_FRAMES][16];

/* Horizon band (map 0x9C00, 3 rows x 32 columns). Sky = colour 1 (tinted by PAL_SKY),
   stars = colour 0, far land = colour 3 with a colour-2 skyline rim so ridges stay
   faintly visible when night crushes sky and land together. */
#define BAND_SKY_TOP     0  /* plain sky, row 0 */
#define BAND_SKY         0  /* plain sky, rows 1-2 (also bg tile 0) */
#define BAND_STAR0       139  /* sky + star (colour 0); variant BAND_STAR0+1 */
#define BAND_LAND        141  /* solid distant land */
#define BAND_RIDGE0      142  /* +k (k=0..7): land fills the bottom k+1 rows, flat top */
#define BAND_SLOPE_UP0   150  /* +k: rises left->right 1 px/px from height k+1 at the left edge */
#define BAND_SLOPE_DN0   158  /* +k: falls left->right to height k+1 at the right edge */

/* ---- sprites: 8x16 OBJ tiles (LCDC.2 = 1), load at 0x8000 ---- */
#define SPR_TILE_COUNT 84    /* <= 128 */
extern const uint8_t spr_tiles[];
/* Player frames are 16x16 = two 8x16 sprites: constant = LEFT half, right half = +2.
   Side frames face RIGHT (X-flip and swap halves for left). */
#define SPR_PL_DOWN0         0
#define SPR_PL_DOWN1         4
#define SPR_PL_UP0           8
#define SPR_PL_UP1           12
#define SPR_PL_SIDE0         16
#define SPR_PL_SIDE1         20
#define SPR_PL_SIT           24
#define SPR_PL_SLEEP         28
#define SPR_PL_GLIDE         32
/* single 8x16 sprites (art in the top 8 px for HUD items, which sit on lines 0-8) */
#define SPR_PIP_FULL         36
#define SPR_PIP_EMPTY        38
#define SPR_ICON_LANTERN     40
#define SPR_ICON_STONES      42
#define SPR_ICON_CLOAK       44
#define SPR_HINT_A           46
#define SPR_BAND_BEACON      48
#define SPR_BAND_BEACON_LIT  50
#define SPR_BAND_HEART       52
#define SPR_BAND_CAIRN       54
#define SPR_RAIN             56
#define SPR_SNOW             58
/* Lantern glow: SPR_GLOW0 is the TOP-LEFT QUARTER (16x16) of a 32x32 dithered disc of light
   centred on the player: SPR_GLOW0 = its left 8x16 half, SPR_GLOW0+2 = its right half. Its
   bottom-right corner is the disc centre. Place 8 sprites (player centre = cx, cy):
       TL: (cx-16, cy-16) GLOW0      (cx-8, cy-16) GLOW0+2          no flip
       TR: (cx,    cy-16) GLOW0+2    (cx+8, cy-16) GLOW0            X flip
       BL: (cx-16, cy)    GLOW0      (cx-8, cy)    GLOW0+2          Y flip
       BR: (cx,    cy)    GLOW0+2    (cx+8, cy)    GLOW0            X+Y flip
   Pixels: colour 1 = brightest (around the feet), 2 = the glow, 3 = its faint outer edge (on DMG
   night ground it vanishes, so the ring fades out). Draw with OPAL_GLOW / DMG OBP1, behind the
   player (higher OAM index than the player). */
#define SPR_GLOW0            60
#define SPR_WATCHER          64  /* 16x32: TL, TR +2, BL +4, BR +6 */
#define SPR_BIRD0            72  /* 2 frames: SPR_BIRD0, SPR_BIRD0+2 (= SPR_BIRD1) */
#define SPR_BIRD1            74
/* map-screen markers (8x16; art centred in the top 8x8, pivot = pixel (3,3)) */
#define SPR_MAP_PLAYER       76
#define SPR_MAP_BEACON       78
#define SPR_MAP_CAIRN        80
#define SPR_MAP_HEART        82

/* ---- palettes ---- */
/* DMG, indexed by PH_DAWN, PH_DAY, PH_DUSK, PH_NIGHT (sound.h). Colour index -> shade
   (0 white .. 3 black); colour 0 (LIGHT) stays white in every phase:
     BGP  dawn  0xA4  0->0 1->1 2->2 3->2   haze: nothing black yet, the land lifted and soft
     BGP  day   0xE4  0->0 1->1 2->2 3->3   identity
     BGP  dusk  0xF4  0->0 1->1 2->3 3->3   detail hardens into black silhouette, the sea goes dark
     BGP  night 0xF8  0->0 1->2 2->3 3->3   ground one step above black (legible), forms black, only light shines
     OBP0 dawn  0xE0  0->0 1->0 2->2 3->3
     OBP0 day   0xE0  0->0 1->0 2->2 3->3
     OBP0 dusk  0xD0  0->0 1->0 2->1 3->3
     OBP0 night 0xD0  0->0 1->0 2->1 3->3
     OBP1 dawn  0x90  0->0 1->0 2->1 3->2
     OBP1 day   0x90  0->0 1->0 2->1 3->2
     OBP1 dusk  0x90  0->0 1->0 2->1 3->2
     OBP1 night 0x90  0->0 1->0 2->1 3->2
   OBP0 = figures (player, band beacon/cairn, icons, map markers); OBP1 = lights
   (warmth pips, lantern glow, rain/snow, Watchers, lit beacon, heart). */
extern const uint8_t dmg_bgp[4];
extern const uint8_t dmg_obp0[4], dmg_obp1[4];
/* CGB: 8 BG palette classes x 4 colours (RGB555) per phase. Colour 0 is always the light. */
enum { PAL_GRASS, PAL_FOREST, PAL_WATER, PAL_SAND, PAL_SNOW, PAL_ROCK, PAL_LIGHT, PAL_SKY };
/* CGB OBJ palette slots (cgb_obj_pal[phase][slot]); DMG palette to use in brackets:
   OPAL_PLAYER [OBP0] wanderer   OPAL_EMBER [OBP1] warmth pips   OPAL_UI [OBP0] item icons,
   hint, map markers   OPAL_WEATHER [OBP1] rain, snow, birds [OBP0]   OPAL_WATCHER [OBP1]
   OPAL_BAND [OBP0] unlit beacon, cairn on the band   OPAL_LIGHT [OBP1] lit beacon, heart
   OPAL_GLOW [OBP1] lantern glow */
enum { OPAL_PLAYER, OPAL_EMBER, OPAL_UI, OPAL_WEATHER, OPAL_WATCHER, OPAL_BAND, OPAL_LIGHT, OPAL_GLOW };
#define DMG_OBP_PLAYER  0   /* OBP0 */
#define DMG_OBP_LIGHT   1   /* OBP1 */
extern const uint16_t cgb_bg_pal[4][8][4];
extern const uint16_t cgb_obj_pal[4][8][4];

/* ---- title screen: load title_tiles at bg tile 0; title_map holds tile indices ---- */
#define TITLE_TILE_COUNT 137
extern const uint8_t title_tiles[];
extern const uint8_t title_map[20 * 18];
extern const uint8_t title_attr[20 * 18];   /* CGB palette 0-7 per cell */
extern const uint16_t title_pal[8][4];

/* ---- map screen tiles (load at bg tile 0; MAP_T_* are indices into map_tiles) ---- */
#define MAP_TILE_COUNT 13
#define MAP_T_FOG        0
#define MAP_T_SHADE0     1
#define MAP_T_SHADE1     2
#define MAP_T_SHADE2     3
#define MAP_T_SHADE3     4
#define MAP_T_TL         5
#define MAP_T_T          6
#define MAP_T_TR         7
#define MAP_T_L          8
#define MAP_T_R          9
#define MAP_T_BL         10
#define MAP_T_B          11
#define MAP_T_BR         12
extern const uint8_t map_tiles[];

#endif
